name: cicd-1
on:
  pull_request:
    types: [opened, synchronize, closed]
    branches: [dev]
    paths:
    - 'my-app/**'

jobs:
  test:
    if: github.event.action == 'opened' || github.event.action == 'synchronize'
    runs-on: ubuntu-lastest
    steps:
    - name: checkout
      uses: actions/checkout@v4

  image-build:
    if: github-event.pull_request.merged == true
    runs-on: ubuntu-lastest
    steps:
    - name: checkout
      uses: actions/checkout@v4

  deploy:
    runs-on: ubuntu-lastest
    needs: [image-build]
    steps:
    - name: checkout
      uses: actions/checkout@v4