name: cicd-1

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches: [dev]
    paths:
    - 'my-app/**'

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'synchronize') }}
    steps:
      - name: checkout
        uses: actions/checkout@v4

  image-build:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    needs: [test]
    steps:
      - name: checkout
        uses: actions/checkout@v4

  deploy:
    runs-on: ubuntu-latest
    needs: [image-build]
    steps:
      - name: checkout
        uses: actions/checkout@v4