name: path_filter
on:
  push:
    paths:
    - '.github/workflows/part1/*'

jobs:
  path_filter:
    runs-on: ubuntu-latest
    steps:
    - name: echo hello dcshin1023
      run: echo hello dcshin1023